# Generated by Django 4.1.1 on 2022-09-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(db_column='brand_id', primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('car_image_id', models.AutoField(db_column='car_image_id', primary_key=True, serialize=False, unique=True)),
                ('car_image_1', models.CharField(blank=True, max_length=700, null=True)),
                ('car_image_2', models.CharField(blank=True, max_length=700, null=True)),
                ('car_image_3', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'car_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(db_column='model_id', primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.AutoField(db_column='segmnet_id', primary_key=True, serialize=False, unique=True)),
                ('segment_name', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'segment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(db_column='version_id', primary_key=True, serialize=False, unique=True)),
                ('version_name', models.CharField(blank=True, max_length=70, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('motor', models.CharField(blank=True, max_length=20, null=True)),
                ('fuelled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('power_hp', models.IntegerField(blank=True, null=True)),
                ('torque', models.IntegerField(blank=True, null=True)),
                ('traction', models.CharField(blank=True, max_length=70, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('radio', models.IntegerField(blank=True, null=True)),
                ('screen', models.IntegerField(blank=True, null=True)),
                ('speakers', models.IntegerField(blank=True, null=True)),
                ('interiors', models.CharField(blank=True, max_length=70, null=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('sunroof', models.IntegerField(blank=True, null=True)),
                ('tires', models.CharField(blank=True, max_length=40, null=True)),
                ('rims', models.CharField(blank=True, max_length=70, null=True)),
                ('color_hexa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'version',
                'managed': False,
            },
        ),
    ]
