# Generated by Django 4.1.1 on 2022-09-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_info_api', '0002_brands_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(db_column='image_id', primary_key=True, serialize=False, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('model_image_id', models.AutoField(db_column='model_image_id', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'model_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VersionImage',
            fields=[
                ('version_image_id', models.AutoField(db_column='version_image_id', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'version_image',
                'managed': False,
            },
        ),
    ]
